
#EurekaClient配置
server:
  port: 9002

spring:
  application:
    name: UserService_Client
  profiles: UserService_Client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true

---
#ConfigClient两环境测试
server: 
  port: 9004
spring: 
  application: 
    name: devConfigClient
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
---
server: 
 port: 9005
spring: 
  application: 
    name: testConfigClient
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
