#EurekaService配置
server:
  port: 9001
  
eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false
---
#EurekaClient配置
server:
  port: 9002

spring:
  application:
    name: UserService_Client
  profiles: UserService_Client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true

---
#ConfigServer
server:
  port: 9003
spring: 
  application: 
    name: ConfigServer
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
---
#ConfigClient两环境配置
server: 
  port: 9004
spring: 
  application: 
    name: devConfigClient
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
---
server: 
 port: 9005
spring: 
  application: 
    name: testConfigClient
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
