#EurekaServer 与 ConfigServer 相互独立（你不注册到我，我也不用你的配置）

---
#EurekaClient配置
server:
  port: 9003

spring:
  application:
    name: UserService_Client
  profiles: UserService_Client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
    register-with-eureka: true

---

#ConfigClient两环境配置
server: 
  port: 9004
spring: 
  application: 
    name: devConfigClient
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
    register-with-eureka: true
---
server: 
 port: 9005
spring: 
  application: 
    name: testConfigClient
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
    register-with-eureka: true
